---
title: "1. The DigiCAT Tool"
---

## Why develop DigiCAT?

Counterfactual analysis provides a set of tools that can help us understand what the active ingredients are in mental health. While the gold standard for doing so would be something like a randomised controlled trial (RCT), RCTs are not always possible and when they are, they are expensive and challenging to do well. Their highly controlled nature also means that they may lack ecological validity so that results from RCTs might not apply very well in the real world.  

As such there is a lot of value in being able to get an idea of what might impact mental health from observational data (I.e., non-experimental data). In fact, there is a wealth of pre-existing mental health data ready to be used in this way. Some examples of such datasets can be found in, for example, this catalogue of mental health datasets: [https://www.cataloguementalhealth.ac.uk/](https://www.cataloguementalhealth.ac.uk/){target="_blank"}  

However, we noticed that counterfactual analysis is not as widely used in mental health research as one might expect. There may be a number of reasons for this but we think a major one is that counterfactual analysis might not be very accessible for mental health researchers. It would not typically be part of training and it can be technically quite complex, which may limit researcher’s ability to use it. There’s also a lack of accessible tools for counterfactual analysis. Most tools require coding skills and while some web applications exist they don’t do everything. In particular, their  functionality tends to be narrowly focused on a particular type of analysis and they tend not be able to deal with the ‘real world’ features of data like the presence of missingness or complex survey data or non-binary treatments. These are things we wanted to address with DigiCAT.  

Another reason we made DigiCAT is we noticed that it took rather a long time to code  counterfactual analyses using existing packages and things got complicated when we had to consider things like missingness, clustering, large numbers of confounders etc.  By pulling together all the code from common ‘journeys’ and creating an easy ‘point and click’ interface we also aim to  speed up the implementation of counterfactual analysis even for expert users adept in the technique in existing softwares like R. 


## How to use DigiCAT

There are two ways to use DigiCAT. The first is to download it and use it on your local computer. This is recommended if you need to avoid uploading your data to a server or if you have a very large dataset or very computationally intensive analyses.  The second way to use it is via the web application. The two versions are mostly very similar but the web application has a few more limits on it.  

__R Package__  

To use DigiCAT on your local computer you should have a recent version of R installed. Within R you can then enter the following lines to install and then run DigiCAT. Once it is installed you only need to run the third line to launch it each time. 

```{r}
#| eval: false
install.packages("remotes") 
remotes::install_github("josiahpjking/DigiCAT@develop")
DigiCAT::run_DigiCAT(enableLocal = TRUE)
```

__Web Version__  

The web version of DigiCAT is available at [https://digicatapp.shinyapps.io/DigiCAT](https://digicatapp.shinyapps.io/DigiCAT){target="_blank"}  

- TODO Tree diagram of DigiCAT options 



## Involving Lived Experience Expertise alongside the Tool 

### Why should the research use Lived Experience expertise ?  

- Reminder of the subjective nature of mental health  
- Bring the Qualitative into the Quantitative analysis  
- Strengthen your research. Increasingly, co-production and PPI (patient and public involvement) is required for funding. This should be taken seriously, rather than treated as an add-on or in a tokenistic way.  
-	Practical application – How does it relate to real experiences? Hone in on practically relevant research questions. Facilitate clinical validity of the interpretation of research findings   
-	Assess likely efficacy in real world application of findings (if applicable)  
- Positive impact for lived experience collaborators. Empowerment, purpose, acquisition of new skills and knowledge, and having a role in changing and improving mental health research and interventions.  

### How should the research use Lived Experience expertise?

There is not one single definition of lived experience, and so it can come in many forms. It might include those who have previously or continue to experience mental illness difficulties, but it can also include family members of those who have experienced it.  

Those with lived experience may already be working in the academy, so it is also fruitful to engage with colleagues (across disciplines) who may bring in a unique lived experience perspective. 

For example, in exploring active ingredients of mental health, a young person’s advisory group were asked to rank their importance, explain reasons, and add other things. This exercise demonstrated that having access to ‘social media’ was a more important factor than initially expected by the researchers.  

Upon further exploration in the advisory group, it was revealed that ‘social media’ was important in order to keep in touch with friends. As one young person pointed out: “It's very important to have a lot of friends and to really stick together because they are one of the only people that are there in all of the situations”. This suggests that exploring use of social media would have been misleading without understanding why the young people thought this was important.  

Similarly, ‘recovery’ can mean different things to different people, and understanding alternative meanings and framings can have a substantial positive impact on the research.
 
As researchers (and individuals) we come to what we do with our set of biases and expectations, it is therefore a good idea to run our interpretations by third parties with lived experience in the area we are wishing to inform.
 

In addition to publishing in scientific journals it is important to present the findings in ways that are easy to understand and utilise for those for whom they are most practically relevant; that is service users and generally those with lived experience. Such communications are best produced in collaboration with them. 

Collaboration with lived experience experts increases credibility and practical reliability and applications of research findings.   


